// tslint:disable
/**
 * JamRoom API
 * The JamRoom API
 *
 * The version of the OpenAPI document: 0.9.26
 * Contact: info@jamroom.pro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * 
 * @export
 * @interface AclClass
 */
export type AclClass  = {
    /**
     * 
     * @type {string}
     * @memberof AclClass
     */
    _class?: string;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof AclClass
     */
    id?: string;
    /**
     * Unique identifier for owner of the object in the system
     * @type {string}
     * @memberof AclClass
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof AclClass
     */
    createdDate?: Date;
    /**
     * Date of object modification
     * @type {Date}
     * @memberof AclClass
     */
    modifiedDate?: Date;
}

export function AclClassFromJSON(json: any): AclClass {
    return {
        '_class': !exists(json, 'class') ? undefined : json['class'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'modifiedDate': !exists(json, 'modifiedDate') ? undefined : new Date(json['modifiedDate']),
    };
}

export function AclClassToJSON(value?: AclClass): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'class': value._class,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'modifiedDate': value.modifiedDate === undefined ? undefined : value.modifiedDate.toISOString(),
    };
}


