// tslint:disable
/**
 * JamRoom API
 * The JamRoom API
 *
 * The version of the OpenAPI document: 0.9.26
 * Contact: info@jamroom.pro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * 
 * @export
 * @interface AclSid
 */
export type AclSid  = {
    /**
     * 
     * @type {string}
     * @memberof AclSid
     */
    sid?: string;
    /**
     * 
     * @type {number}
     * @memberof AclSid
     */
    principal?: number;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof AclSid
     */
    id?: string;
    /**
     * Unique identifier for owner of the object in the system
     * @type {string}
     * @memberof AclSid
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof AclSid
     */
    createdDate?: Date;
    /**
     * Date of object modification
     * @type {Date}
     * @memberof AclSid
     */
    modifiedDate?: Date;
}

export function AclSidFromJSON(json: any): AclSid {
    return {
        'sid': !exists(json, 'sid') ? undefined : json['sid'],
        'principal': !exists(json, 'principal') ? undefined : json['principal'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'modifiedDate': !exists(json, 'modifiedDate') ? undefined : new Date(json['modifiedDate']),
    };
}

export function AclSidToJSON(value?: AclSid): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'sid': value.sid,
        'principal': value.principal,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'modifiedDate': value.modifiedDate === undefined ? undefined : value.modifiedDate.toISOString(),
    };
}


