// tslint:disable
/**
 * JamRoom API
 * The JamRoom API
 *
 * The version of the OpenAPI document: 0.9.26
 * Contact: info@jamroom.pro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';
import {
    Address,
    AddressFromJSON,
    AddressToJSON,
} from './';


// thorapi

/**
 * 
 * @export
 * @interface Organization
 */
export type Organization  = {
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    homePage?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    addressId?: string;
    /**
     * 
     * @type {Address}
     * @memberof Organization
     */
    address?: Address;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof Organization
     */
    id?: string;
    /**
     * Unique identifier for owner of the object in the system
     * @type {string}
     * @memberof Organization
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof Organization
     */
    createdDate?: Date;
    /**
     * Date of object modification
     * @type {Date}
     * @memberof Organization
     */
    modifiedDate?: Date;
}

export function OrganizationFromJSON(json: any): Organization {
    return {
        'name': json['name'],
        'homePage': !exists(json, 'homePage') ? undefined : json['homePage'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'addressId': !exists(json, 'addressId') ? undefined : json['addressId'],
        'address': !exists(json, 'address') ? undefined : AddressFromJSON(json['address']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'modifiedDate': !exists(json, 'modifiedDate') ? undefined : new Date(json['modifiedDate']),
    };
}

export function OrganizationToJSON(value?: Organization): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'homePage': value.homePage,
        'phone': value.phone,
        'addressId': value.addressId,
        'address': AddressToJSON(value.address),
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'modifiedDate': value.modifiedDate === undefined ? undefined : value.modifiedDate.toISOString(),
    };
}


