// tslint:disable
/**
 * JamRoom API
 * The JamRoom API
 *
 * The version of the OpenAPI document: 0.9.26
 * Contact: info@jamroom.pro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * 
 * @export
 * @interface Role
 */
export type Role  = {
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    userId?: string;
    /**
     * the role
     * @type {string}
     * @memberof Role
     */
    roleName?: RoleRoleNameEnum;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof Role
     */
    id?: string;
    /**
     * Unique identifier for owner of the object in the system
     * @type {string}
     * @memberof Role
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof Role
     */
    createdDate?: Date;
    /**
     * Date of object modification
     * @type {Date}
     * @memberof Role
     */
    modifiedDate?: Date;
}

export function RoleFromJSON(json: any): Role {
    return {
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'roleName': !exists(json, 'roleName') ? undefined : json['roleName'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'modifiedDate': !exists(json, 'modifiedDate') ? undefined : new Date(json['modifiedDate']),
    };
}

export function RoleToJSON(value?: Role): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'userId': value.userId,
        'roleName': value.roleName,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'modifiedDate': value.modifiedDate === undefined ? undefined : value.modifiedDate.toISOString(),
    };
}

/**
* @export
* @enum {string}
*/
export enum RoleRoleNameEnum {
    Anonymous = 'ANONYMOUS',
    Customer = 'CUSTOMER',
    Staff = 'STAFF',
    Admin = 'ADMIN'
}


