// tslint:disable
/**
 * JamRoom API
 * The JamRoom API
 *
 * The version of the OpenAPI document: 0.9.26
 * Contact: info@jamroom.pro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * 
 * @export
 * @interface AclEntry
 */
export type AclEntry  = {
    /**
     * 
     * @type {number}
     * @memberof AclEntry
     */
    aclObjectIdentity?: number;
    /**
     * 
     * @type {number}
     * @memberof AclEntry
     */
    aceOrder?: number;
    /**
     * 
     * @type {number}
     * @memberof AclEntry
     */
    sid?: number;
    /**
     * 
     * @type {number}
     * @memberof AclEntry
     */
    mask?: number;
    /**
     * 
     * @type {number}
     * @memberof AclEntry
     */
    granting?: number;
    /**
     * 
     * @type {number}
     * @memberof AclEntry
     */
    auditSuccess?: number;
    /**
     * 
     * @type {number}
     * @memberof AclEntry
     */
    auditFailure?: number;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof AclEntry
     */
    id?: string;
    /**
     * Unique identifier for owner of the object in the system
     * @type {string}
     * @memberof AclEntry
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof AclEntry
     */
    createdDate?: Date;
    /**
     * Date of object modification
     * @type {Date}
     * @memberof AclEntry
     */
    modifiedDate?: Date;
}

export function AclEntryFromJSON(json: any): AclEntry {
    return {
        'aclObjectIdentity': !exists(json, 'acl_object_identity') ? undefined : json['acl_object_identity'],
        'aceOrder': !exists(json, 'ace_order') ? undefined : json['ace_order'],
        'sid': !exists(json, 'sid') ? undefined : json['sid'],
        'mask': !exists(json, 'mask') ? undefined : json['mask'],
        'granting': !exists(json, 'granting') ? undefined : json['granting'],
        'auditSuccess': !exists(json, 'audit_success') ? undefined : json['audit_success'],
        'auditFailure': !exists(json, 'audit_failure') ? undefined : json['audit_failure'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'modifiedDate': !exists(json, 'modifiedDate') ? undefined : new Date(json['modifiedDate']),
    };
}

export function AclEntryToJSON(value?: AclEntry): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'acl_object_identity': value.aclObjectIdentity,
        'ace_order': value.aceOrder,
        'sid': value.sid,
        'mask': value.mask,
        'granting': value.granting,
        'audit_success': value.auditSuccess,
        'audit_failure': value.auditFailure,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'modifiedDate': value.modifiedDate === undefined ? undefined : value.modifiedDate.toISOString(),
    };
}


