// tslint:disable
/**
 * JamRoom API
 * The JamRoom API
 *
 * The version of the OpenAPI document: 0.9.26
 * Contact: info@jamroom.pro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * 
 * @export
 * @interface Address
 */
export type Address  = {
    /**
     * full name of addressee
     * @type {string}
     * @memberof Address
     */
    name: string;
    /**
     * street address line 1
     * @type {string}
     * @memberof Address
     */
    street1: string;
    /**
     * full name of city
     * @type {string}
     * @memberof Address
     */
    city: string;
    /**
     * State of residence 2-character code (USA)
     * @type {string}
     * @memberof Address
     */
    state: string;
    /**
     * 5+4 digit zip code
     * @type {string}
     * @memberof Address
     */
    postalCode: string;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasWifi?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    userId?: string;
    /**
     * The type of address
     * @type {string}
     * @memberof Address
     */
    addressType?: AddressAddressTypeEnum;
    /**
     * street address line 2
     * @type {string}
     * @memberof Address
     */
    street2?: string;
    /**
     * 3 character country code (upper case)
     * @type {string}
     * @memberof Address
     */
    country?: string;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof Address
     */
    id?: string;
    /**
     * Unique identifier for owner of the object in the system
     * @type {string}
     * @memberof Address
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof Address
     */
    createdDate?: Date;
    /**
     * Date of object modification
     * @type {Date}
     * @memberof Address
     */
    modifiedDate?: Date;
}

export function AddressFromJSON(json: any): Address {
    return {
        'name': json['name'],
        'street1': json['street1'],
        'city': json['city'],
        'state': json['state'],
        'postalCode': json['postal_code'],
        'hasWifi': !exists(json, 'hasWifi') ? undefined : json['hasWifi'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'addressType': !exists(json, 'addressType') ? undefined : json['addressType'],
        'street2': !exists(json, 'street2') ? undefined : json['street2'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'modifiedDate': !exists(json, 'modifiedDate') ? undefined : new Date(json['modifiedDate']),
    };
}

export function AddressToJSON(value?: Address): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'street1': value.street1,
        'city': value.city,
        'state': value.state,
        'postal_code': value.postalCode,
        'hasWifi': value.hasWifi,
        'userId': value.userId,
        'addressType': value.addressType,
        'street2': value.street2,
        'country': value.country,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'modifiedDate': value.modifiedDate === undefined ? undefined : value.modifiedDate.toISOString(),
    };
}

/**
* @export
* @enum {string}
*/
export enum AddressAddressTypeEnum {
    Home = 'home',
    Mail = 'mail',
    Work = 'work',
    School = 'school',
    Other = 'other'
}


